// Code generated by cmd/genrunners; DO NOT EDIT.

package cmd

import (
	"fmt"
	y2015d1 "github.com/sirgwain/advent-of-code/advent/2015/day1"
	y2015d2 "github.com/sirgwain/advent-of-code/advent/2015/day2"
	y2015d3 "github.com/sirgwain/advent-of-code/advent/2015/day3"
	y2015d4 "github.com/sirgwain/advent-of-code/advent/2015/day4"
	y2015d5 "github.com/sirgwain/advent-of-code/advent/2015/day5"
	y2015d6 "github.com/sirgwain/advent-of-code/advent/2015/day6"
)

type runner interface {
	Run([]byte) (int, int, error)
}

type dayRunner struct {
	r    runner
	year int
	day  int
}

func getRunner(year, day int) (dayRunner, error) {
	var r runner
	switch year {
	case 2015:
		switch day {
		case 1:
			r = &y2015d1.Day{}
		case 2:
			r = &y2015d2.Day{}
		case 3:
			r = &y2015d3.Day{}
		case 4:
			r = &y2015d4.Day{}
		case 5:
			r = &y2015d5.Day{}
		case 6:
			r = &y2015d6.Day{}
		}
	}

	if r == nil {
		return dayRunner{}, fmt.Errorf("day %d/%d not found", year, day)
	}
	return dayRunner{r: r, year: year, day: day}, nil
}

func getAllRunners() []dayRunner {
	runners := make([]dayRunner, 0, 6)
	runners = append(runners, dayRunner{r: &y2015d1.Day{}, year: 2015, day: 1})
	runners = append(runners, dayRunner{r: &y2015d2.Day{}, year: 2015, day: 2})
	runners = append(runners, dayRunner{r: &y2015d3.Day{}, year: 2015, day: 3})
	runners = append(runners, dayRunner{r: &y2015d4.Day{}, year: 2015, day: 4})
	runners = append(runners, dayRunner{r: &y2015d5.Day{}, year: 2015, day: 5})
	runners = append(runners, dayRunner{r: &y2015d6.Day{}, year: 2015, day: 6})

	return runners
}
